[package]
name = "cardgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.gtk]
version = "0.8.1"

[dependencies.gdk]
version = "0.12.1"

[dependencies.glib]
version = "0.9.3"
